config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :occupants, controllers: {
    registrations: "occupants/registrations",
    sessions: "occupants/sessions"
  }
  devise_for :owners, controllers: {
    registrations: "owners/registrations",
    sessions: "owners/sessions"
  }
  
  resources :rooms
  get "rooms/:id/images", to: "rooms#images", as: "room_images"
  
  get "locations/new", to: "locations#new", as: "new_location"
  post "locations", to: "locations#create"
  delete "locations/:id", to: "locations#destroy", as: "location"
  get "/sign_in", to: "pages#options"

  post "room/:room_id/reviews", to: "reviews#create", as: "room_reviews"
  get "room/:room_id/reviews/:review_id/edit", to: "reviews#edit", as: "edit_room_review"
  patch "room/:room_id/reviews/:review_id", to: "reviews#update", as: "room_review"
  delete "room/:room_id/reviews/:review_id", to: "reviews#destroy"

  get "dashboard", to: "pages#dashboard", as: "dashboard"

  get "maps/render/location/:location_id", to: "maps#location_map", as: "location_map"
  get "maps/marker", to: "maps#marker_map", as: "marker_map"
  get "maps/results", to: "maps#results_map", as: "results_map"

  devise_scope :owner do
    get "owners", to: "owners/registrations#edit"
    get "owners/password", to: "owners/passwords#new"
  end

  devise_scope :occupant do
    get "occupants", to: "occupants/registrations#edit"
    get "occupants/password", to: "occupants/passwords#new"
  end
end

app/views/pages/dashboard/_locations.html.erb
<% locations.each do |location| %>
  <div class="db-location d-flex align-items-center mb-3" id="<%= dom_id(location) %>">
    <%= link_to dashboard_path(location: location), style: "text-decoration: none;", data: { turbo_frame: "dashboard_rooms_frame" }, class: "w-80" do %>
      <h6 class="monsterrat heading-color semiBold m-0"><%= location.name %></h6>
      <div class="d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="#59657c" aria-hidden="true" style="width: 15px; height: 15px;">
          <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd"></path>
        </svg>
        <p class="db-subheading px-1 m-0"><%= "#{location.unit}, #{location.address_line}, #{location.city}" %></p>
      </div>
    <% end %>
    <div class="w-20 d-flex align-items-center justify-content-around">
      <%= button_to " ", location_map_path(location), method: :get, data: { "turbo-frame": "location_map_frame" }, class: "db-map" %>
      <%= button_to " ", location_path(location), method: :delete, class: "db-delete", data: { "turbo-confirm": "Deleting a location will also delete all rooms associated with it. Continue?" } %>
    </div>
  </div>
<% end %>

app/views/pages/dashboard/_rooms.html.erb
<%= turbo_frame_tag "dashboard_rooms_frame" do %>
  <% if @rooms.blank? %>
    <p class="quicksand heading-color text-center nothing" style="font-weight: 700px;">No rooms to display.</p>
  <% else %>
    <% rooms.each do |room| %>
      <div class="db-room d-flex align-items-center mb-3" id="<%= dom_id(room) %>">
        <%= link_to room_path(room), class: "w-75 text-decoration-none" do %>
          <h6 class="m-0 monsterrat heading-color semiBold"><%= room.name %></h6>
          <div class="d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="#59657c" aria-hidden="true" style="width: 15px; height: 15px;">
              <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd"></path>
            </svg>
            <p class="db-subheading px-1 m-0"><%= room.location.name %></p>
          </div>
        <% end %>
        <div class="w-25 d-flex align-items-center justify-content-around">
          <%= button_to " ", edit_room_path(room), method: :get, class: "db-edit" %>
          <%= button_to " ", room_path(room), method: :delete, class: "db-delete", data: { "turbo-confirm": "Are you sure you want to delete this room?" } %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>