config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :occupants, controllers: {
    registrations: "occupants/registrations",
    sessions: "occupants/sessions"
  }
  devise_for :owners, controllers: {
    registrations: "owners/registrations",
    sessions: "owners/sessions"
  }
  
  resources :rooms
  get "rooms/:id/images", to: "rooms#images", as: "room_images"
  
  get "locations/new", to: "locations#new", as: "new_location"
  post "locations", to: "locations#create"
  delete "locations/:id", to: "locations#destroy", as: "location"
  get "/sign_in", to: "pages#options"

  post "room/:room_id/reviews", to: "reviews#create", as: "room_reviews"
  get "room/:room_id/reviews/:review_id/edit", to: "reviews#edit", as: "edit_room_review"
  patch "room/:room_id/reviews/:review_id", to: "reviews#update", as: "room_review"
  delete "room/:room_id/reviews/:review_id", to: "reviews#destroy"

  get "dashboard", to: "pages#dashboard", as: "dashboard"

  get "maps/render/location/:location_id", to: "maps#location_map", as: "location_map"
  get "maps/marker", to: "maps#marker_map", as: "marker_map"
  get "maps/results", to: "maps#results_map", as: "results_map"

  devise_scope :owner do
    get "owners", to: "owners/registrations#edit"
    get "owners/password", to: "owners/passwords#new"
  end

  devise_scope :occupant do
    get "occupants", to: "occupants/registrations#edit"
    get "occupants/password", to: "occupants/passwords#new"
  end
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, :description, :rent, :capacity, :vacancies, presence: true
  validates :capacity, :vacancies, numericality: { only_integer: true, greater_than: 0 }
  validates :rent, numericality: { only_numeric: true, in: 1000..20000 }
  delegate :owner, to: :location
  belongs_to :location
  has_many :reviews, dependent: :destroy
  has_many_attached :images, dependent: :destroy

  scope :includes_attachments, -> { includes(images_attachments: :blob)
    .includes(images_attachments: { blob: :variant_records }) }

  scope :includes_all, -> { includes(:location).includes_attachments }

  def image_variant image, width=400, height=400
    # libvips is required for image variants
    # uncomment the next line if production server does not support installation of libvips
    # return image if Rails.env.production?
    return unless image.content_type.in?(%w[ image/jpeg image/png ])
    image.variant(resize_to_limit: [width, height]).processed
  rescue
    "image-load-failed.svg"
  end

  def self.default_order
    self.includes(:location).order(updated_at: :desc)
  end

  def self.where_order_maintained room_ids
    self.includes_all
      .where(id: room_ids)
      .order(Arel.sql("position(id::text in '#{room_ids.join(',')}')"))
  end
  
  def self.rentables location_ids, rent, sort_option={}
    self.includes_all
      .where(location: location_ids, rent: ..rent)
      .order(sort_option)
  end

  def self.rentable_ids locations, rent
    locations.flat_map do |location|
      location.rooms.flat_map do |room|
        room.id if rent >= room.rent
      end
    end.compact
  end

  def self.sort_option param
    a, b = param&.split("-")
    if a.blank? or b.blank? or %w[ distance rent updated_at ].exclude?(a) or %w[ asc desc ].exclude?(b)
      { updated_at: :desc }
    else
      Hash[a.to_sym, b.to_sym]
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include RoomsHelper
  include Pagy::Backend
  before_action :authenticate_owner!, except: %i[ index show images ]
  before_action :set_room, only: %i[ show edit update destroy images ]
  before_action :room_ownership, only: %i[ edit update destroy ]
  before_action :set_locations, :locations_count, only: %i[ new edit ]
  before_action :validate_images, only: %i[ create ]
  before_action :set_search_params, :set_rooms, only: %i[ index ]

  def index
    if @rooms.blank?
      @pagy, @pagy_rooms = pagy(Room.default_order)
      flash.now.alert = "No match found. Displaying all rooms." if @place.present? and notify?
    else
      @pagy, @pagy_rooms = pagy(@rooms)
      flash.now.notice = "#{view_context.pluralize(@rooms.size, "room")} found." if notify?
    end
  end

  def show
    @tags = Tag.where(id: @room.tags)
    if occupant_signed_in?
      @review = @room.reviews.find_by(occupant: current_occupant)
      @reviews = @room.reviews.where.not(occupant: current_occupant).order(updated_at: :desc)
    else
      @review = nil
      @reviews = @room.reviews.order(updated_at: :desc)
    end
  end

  def new
    @tags = Tag.names_to_hash
    @room = Room.new
  end

  def create
    @room = Room.new(room_params.except(:location))
    @room.location = Location.find(room_params[:location]) if room_params[:location].present?

    if @room.save
      redirect_to room_path(@room), notice: "Room was successfully listed."
    else
      redirect_to new_room_path, alert: "Room was not listed.", status: 302
    end
  end

  def edit
    @tags = Tag.names_to_hash
  end

  def update
    @room.images.purge
    @room.location = Location.find(room_params[:location]) if room_params[:location].present? 

    if @room.update(room_params.except(:location))
      redirect_to room_path(@room), notice: "Room details was successfully updated."
    else
      redirect_to edit_room_path(@room), alert: "Room was not updated.", status: 302
    end
  end

  def destroy
    @room.images.purge
    @room.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@room) }
      format.html         { redirect_to dashboard_path }
    end
  end

  def images
    if params[:active].present?
      @active = @room.images.find(params[:active])&.id
    else
      @active = @room.images.first&.id
    end
    render partial: "images"
  end

  private
  def room_ownership
    redirect_to root_path unless current_owner&.rooms.include?(@room)
  end

  def locations_count
    redirect_to new_location_path, alert: "You must add a location first." if current_owner&.locations.count.zero?
  end

  def set_room
    @room = Room.includes_attachments.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name, :rent, :capacity, :vacancies, :description, :location, tags: [], images: [])
  end

  def set_rooms
    if @place.present?
      if @sort_option.has_key?(:distance)
        locations = Location.order_near(@place, @distance, @sort_option)
        room_ids = Room.rentable_ids(locations, @rent)
        @rooms = Room.where_order_maintained(room_ids)
      else
        location_ids = Location.near_ids(@place, @distance)
        @rooms = Room.rentables(location_ids, @rent, @sort_option)
      end
    else
      @rooms = Room.includes_all.order(@sort_option)
    end
  end

  def set_locations
    @locations = current_owner.locations
  end

  def validate_images
    return if room_params[:images].nil?
    room_params[:images].each do |image|
      if image.size > 4.megabytes
        flash.alert = "Please upload images less than 4MB in size."
        redirect_to new_room_path, status: :unprocessable_entity
      elsif !image.content_type.in?(%w[ image/jpeg image/png ])
        flash.alert = "Please upload images in jpeg or png format."
        redirect_to new_room_path, status: :unprocessable_entity
      end
    end
  end

  def search_params
    params.permit(:place, :distance, :rent, :sort, :commit)
  end

  def set_search_params
    @place = search_params[:place]
    @center = Location.geocode_place(@place)
    @distance = search_params[:distance]&.to_i || 20
    @rent = search_params[:rent]&.to_f || 20000
    @sort_option = Room.sort_option(search_params[:sort])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  include Pagy::Frontend

  def notify?
    params[:page].blank? and params[:commit] == "Search"
  end

  def allowed_to_write_review?
    occupant_signed_in? and @room.owner.email != current_occupant&.email
  end

  def image_link_to_images room, image
    body = image_tag(room.image_variant(image, 800, 450))
    url = room_images_path(room, active: image.id)
    options = {
      data: { turbo_frame: "room_images_frame", action: "click->room#showImages" }
    }
    
    link_to(body, url, options)
  end

  def options_for_location location
    {
      place: "#{location.latitude}, #{location.longitude}",
      distance: 1,
      sort: "distance-asc"
    }
  end
end

app/views/rooms/_carousel.html.erb
<% if @room.images.present? and @room.images.count > 1 %>
  <div class="multi-carousel mb-5" id="carousel" data-mdb-items="2">
    <div class="multi-carousel-inner">
      <% @room.images.each do |image| %>
        <div class="multi-carousel-item" style="width: 50%; margin-left: 0px;">
          <%= image_link_to_images(@room, image) %>
        </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" tabindex="0" data-mdb-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    </button>
    <button class="carousel-control-next" type="button" tabindex="0" data-mdb-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
    </button>
  </div>
  <%= javascript_include_tag "carousel.js" %>
<% elsif @room.images.present? %>
  <div class="mb-5 w-fit mx-auto">
    <%= image_link_to_images(@room, @room.images.first) %>
  </div>
<% else %>
  <%= image_tag "nia.png", class: "d-block mx-auto mb-5", style: "height: 400px;" %>
<% end %>

app/views/rooms/_contact.html.erb
<% if occupant_signed_in? or owner_signed_in? %>
  <div class="text-center quicksand grey" style="font-size: 15px;">
    <div class="d-flex align-items-center">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" stroke-width="5" stroke="#59657c" fill="none" style="width: 15px; height: 15px;"><circle cx="32" cy="18.14" r="11.14"/><path d="M54.55,56.85A22.55,22.55,0,0,0,32,34.3h0A22.55,22.55,0,0,0,9.45,56.85Z"/></svg>
      <span class="quicksand grey px-1 semiBold" style="font-size: 15px;">: <%= @room.owner.name %></span>
    </div>
    <div class="d-flex align-items-center">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" stroke-width="5" stroke="#59657c" fill="none" style="width: 15px; height: 15px;"><path d="M11.11,8.4a2.62,2.62,0,0,0-2.53,2.78c.35,6,2,20.64,9.9,29.77,9.46,11,21.78,14.79,34.42,14.23a2.68,2.68,0,0,0,2.52-2.65V42.92a4,4,0,0,0-3.09-3.86L46,37.66a4,4,0,0,0-4.16,1.69l-1.4,2.12a1,1,0,0,1-1.22.37C36,40.45,23.17,34.45,21.76,24.33a1,1,0,0,1,.48-1l2.54-1.55a4,4,0,0,0,1.81-4.21L25.2,11.13a4,4,0,0,0-4-3.12Z"/></svg>
      <span class="quicksand grey px-1 semiBold" style="font-size: 15px;">: <%= @room.owner.contact %></span>
    </div>
    <div class="d-flex align-items-center">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" stroke-width="5" stroke="#59657c" fill="none" style="width: 15px; height: 15px;"><rect x="7.1" y="9.65" width="49.8" height="44.71" rx="2.5"/><polyline points="7.88 9.65 33.04 31.62 56.15 10.37"/></svg>
      <span class="quicksand grey px-1 semiBold" style="font-size: 15px;">: <%= mail_to @room.owner.email, style: "text-decoration: none;" %></span>
    </div>
  </div>
<% else %>
  <p class="quicksand grey mt-3" style="font-size: 15px;">
    Please <%= link_to "sign in", sign_in_path, class: "text-decoration-none semiBold", style: "color: #3c529c" %> to your account to see contact information.
  </p>
<% end %>

app/views/rooms/_details.html.erb
<div class="text-center quicksand grey mt-5" style="font-size: 15px;">
  <div class="d-flex align-items-center mb-1">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" style="width: 15px; height: 15px;">
      <path d="M6 9.5V14.5M18 9.5V14.5M3.11111 6H20.8889C21.5025 6 22 6.53726 22 7.2V16.8C22 17.4627 21.5025 18 20.8889 18H3.11111C2.49746 18 2 17.4627 2 16.8V7.2C2 6.53726 2.49746 6 3.11111 6ZM14.5 12C14.5 13.3807 13.3807 14.5 12 14.5C10.6193 14.5 9.5 13.3807 9.5 12C9.5 10.6193 10.6193 9.5 12 9.5C13.3807 9.5 14.5 10.6193 14.5 12Z" stroke="#59657c" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
    <span class="quicksand grey px-1" style="font-size: 15px;">Rent starts at: <span class="semiBold"><%= number_to_currency(@room.rent, unit: "₱") %></span></span>
  </div>
  <div class="d-flex align-items-center">
    <svg xmlns="http://www.w3.org/2000/svg" fill="#59657c" viewBox="0 0 512 512" enable-background="new 0 0 512 512" style="width: 15px; height: 15px;">
      <g>
        <path d="m496 320c0-15.581 0-282.497 0-296 0-8.836-7.163-16-16-16s-16 7.164-16 16v16h-416v-16c0-8.836-7.164-16-16-16s-16 7.164-16 16v296c-8.836 0-16 7.164-16 16v152c0 8.836 7.164 16 16 16h56c6.061 0 11.601-3.424 14.311-8.845l19.578-39.155h300.223l19.578 39.155c2.71 5.421 8.25 8.845 14.311 8.845h56c8.837 0 16-7.164 16-16v-152c-.001-8.836-7.164-16-16.001-16zm-32-91.833c-11.449-7.679-25.209-12.167-40-12.167h-56v-32c0-35.29-28.71-64-64-64h-96c-35.29 0-64 28.71-64 64v32h-56c-14.791 0-28.551 4.488-40 12.167v-156.167h416zm-128-12.167h-160v-32c0-17.645 14.355-32 32-32h96c17.645 0 32 14.355 32 32zm-288 72c0-22.056 17.944-40 40-40h336c22.056 0 40 17.944 40 40v32h-416zm432 184h-30.111l-19.578-39.155c-2.71-5.421-8.25-8.845-14.311-8.845h-320c-6.061 0-11.601 3.424-14.311 8.845l-19.578 39.155h-30.111v-120h448z"/>
      </g>
    </svg>
    <span class="quicksand grey px-1" style="font-size: 15px;">
      Vacancies: <span class="semiBold"><%= pluralize(@room.vacancies, "bed") %></span> remaining</span>
    </span>
  </div>
</div>

app/views/rooms/_form.html.erb
<%= form_with(model: room, class: "d-flex justify-content-center") do |f| %>
  <div class="form-lg shadow-lg p-5">
    <% if room.name == "" %>
        <h3 class="text-center monsterrat heading-color semiBold mb-5">List Room</h3>
    <% else %>
        <h3 class="text-center monsterrat heading-color semiBold mb-3">Edit <%= room.name %></h3>
    <% end %>
    <div class="d-flex flex-row">
      <div class="w-50 me-5">
        <p class="mb-1 ps-1 monsterrat" style="font-size: 0.9em;">What is the name of the room? <i style="font-size: 0.8em;">(e.g., Room T, Unit 23, 303)</i></p>
        <div class="form-floating mb-3">
          <%= f.text_field :name, class: "form-control", placeholder: "Name", autofocus: true, required: true %>
          <%= f.label :name, style: "display: block" %>
        </div>

        <p class="mb-1 ps-1 monsterrat" style="font-size: 0.9em;">Write a short description detailing what can be found or what is unique in the room.</p>
        <div class="form-floating mb-3">
          <%= f.text_area :description, class: "form-control", placeholder: "Description", style: "height: 150px; resize: none;", required: true %>
          <%= f.label :description, style: "display: block" %>
        </div>

        <p class="mb-1 ps-1 monsterrat" style="font-size: 0.9em;">What is the starting rental price?</p>
        <div class="form-floating mb-3">
          <%= f.number_field :rent, class: "form-control", placeholder: "Rent", required: true, value: 3000.00, min: 1000, max: 20000, step: 100 %>
          <%= f.label :rent, style: "display: block" %>
        </div>

        <p class="mb-1 ps-1 monsterrat" style="font-size: 0.9em;">What is the maximum number of occupants that can stay in this room?</p>
        <div class="form-floating mb-3">
          <%= f.number_field :capacity, class: "form-control", placeholder: "Capacity", required: true, value: 4, min: 1 %>
          <%= f.label :capacity, style: "display: block" %>
        </div>

        <p class="mb-1 ps-1 monsterrat" style="font-size: 0.9em;">How many vacancies are left?</p>
        <div class="form-floating mb-3">
          <%= f.number_field :vacancies, class: "form-control", placeholder: "Vacancies", required: true, value: 4, min: 1 %>
          <%= f.label :vacancies, style: "display: block" %>
        </div>

        <div class>
          <%= f.label :images, style: "display: block", class: "form-label d-inline-block" %>
          <span class="mb-1 ps-1 monsterrat" style="font-size: 0.9em;">
            <i style="font-size: 0.8em;">(less than 4MB, .jpeg or .png, 16:9 or 3:2 aspect-ratio)</i>
          </span>
          <%= f.file_field :images, class: "form-control", multiple: true, accept: "image/png,image/jpeg", include_hidden: false %>
        </div>
      </div>

      <div class="w-50">          
        <div class="mb-4">
          <div class="d-flex w-100 justify-content-between">
            <span>Locations</span>
            <span class="links text-right quicksand semiBold"><%= link_to "+ Add New Location", new_location_path %></span>
          </div>
          <% unless current_owner.locations.blank? %>
            <div class="d-flex flex-wrap align-items-center justify-content-between w-100">
            <% locations.each do |location| %>
              <div class="form-check w-50">
                <%= f.radio_button :location, location.id, class:"form-check-input", required: true %>
                <%= f.label "location_#{location.id}", location.name, class:"form-check-label"%>
              </div>
            <% end %>
            </div>
          <% end %>
        </div>

        <div class="mb-4">
          <div class="mb-1">Tags</div>
          <div class="d-flex flex-wrap align-items-center justify-content-between w-100">
          <%= f.collection_check_boxes(:tags, @tags, :last, :first, include_hidden: false) do |box| %>       
            <div class="form-check" style="width: 30%;">
              <%= box.check_box class: "form-check-input", checked: room.tags&.include?(box.object.last.to_s) %>
              <%= box.label class: "form-check-label" %>
            </div>
          <% end %>
          </div>
        </div>

        <div class="actions d-flex align-items-content justify-content-center mb-3 mt-4">
          <%= f.submit "Post" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/rooms/_room_description.html.erb
<div class="d-flex align-items-start justify-content-evenly w-100 mb-sr">
  <div style="width: 40%;">
    <div class="w-100 d-flex flex-column">
      <h3 class="monsterrat heading-color bold"><%= @room.name %></h3>
      <div class="d-flex align-items-center mb-3 px-3 w-fit" style="border-radius: 15px; border: 1px solid rgba(60, 82, 156, 0.3);">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="#59657c" aria-hidden="true" style="width: 15px; height: 15px;">
          <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd"></path>
        </svg>
        <%= link_to rooms_path(options_for_location(@room.location)), style: "text-decoration: none" do %>
          <span class="quicksand grey px-1" style="font-size: 15px;"><%= @room.location.name %>, <%= @room.location.city %></span>
        <% end %>
      </div>
      <p class="quicksand grey" style="font-size: 15px;" ><%= @room.description %></p>
      <div>
        <%= render "contact" %>
      </div>
    </div>
  </div>

  <div style="width: 40%;">
    <%= render "details" %>
    <div class="w-100 h-5 d-flex flex-wrap align-items-center justify-content-start mt-3">
      <% @tags.each do |tag| %>
        <div class="tag-img d-flex align-items-center justify-content-start" style="width: 33%;">
          <%= image_tag(tag.icon) if tag.icon %>
          <span class="quicksand light-grey mx-2" style="font-size: 15px;"><%= tag.name %></span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/_search_form.html.erb
<div class="d-flex justify-content-between flex-grow-1">
  <div data-room-target="formBackdrop" data-action="click->room#hideForm" class="backdrop d-none"></div>
  <button data-action="click->room#showForm" class="adv-search rounded px-3 ms-2">Advanced Search</button>
  <div>
    <div>
      <% if @place.present? and @rooms.present? %>
        <span class="quicksand me-2">
          Found <%= pluralize(@rooms.size, "room") %> within <span class="heading-color" style="font-weight: 700;"><%= @distance %>km</span> of <span class="heading-color" style="font-weight: 700;"><%= @place.titleize %></span> (max rent: <span class="heading-color" style="font-weight: 700;"><%= number_to_currency(@rent, unit: "₱") %></span>)
        </span>
      <% elsif @place.present? %>
        <span class="quicksand me-2">
          No rooms within <span class="heading-color" style="font-weight: 700;"><%= @distance %>km</span> of <span class="heading-color" style="font-weight: 700;"><%= @place.titleize %></span> (max rent: <span class="heading-color" style="font-weight: 700;"><%= number_to_currency(@rent, unit: "₱") %></span>)
        </span>
      <% end %>
      <%= link_to "Show rooms on map", results_map_path(map_params), class: "view-results" %>
    </div>
  </div>
  <%= form_with(url: rooms_url, method: :get, data: { room_target: "form", action: "submit->room#hideForm" },
    class:"d-none search-form") do |f| %>
    <div class="form-floating mb-3">
      <%= f.search_field :place, placeholder: "enter a place or landmark",
        class: "form-control quicksand", spellcheck: false, required: true, value: params[:place] %>
      <%= f.label :place, 'Place or Landmark', style: "display: block", class: "quicksand grey" %>
    </div>

    <div class="slidecontainer">
      <p>Max Distance: <span data-room-target="distance"></span>km</p>
      <%= f.range_field :distance, in: 1..20, class: "slider", value: @distance,
        data: { room_target: "distanceSlider" } %>
    </div>
    
    <div class="slidecontainer">
      <p>Max Rent: ₱<span data-room-target="rent"></span></p>
      <%= f.range_field :rent, in: 1000..20000, step: 100, class: "slider", value: @rent,
        data: { room_target: "rentSlider" } %>
    </div>

    <div class="select-dd mb-5">
      <%= f.select(:sort, [
      ["Distance - nearest to farthest", "distance-asc"],
      ["Distance - farthest to nearest", "distance-desc"],
      ["Rent - lowest to highest", "rent-asc"],
      ["Rent - highest to lowest", "rent-desc"],
      ["Newest", "updated_at-desc"],
      ["Oldest", "updated_at-asc"],
      ], selected: selected, prompt: "All rooms") %>
    </div>

    <%= f.submit :Search, style: "display: block", class: "mx-auto submit" %>
  <% end %>
</div>

app/views/rooms/_select_form.html.erb
<form action="<%= rooms_url %>" method="get" data-room-target="selectForm">
  <input type="text" hidden value="<%= @place %>" name="place">
  <input type="text" hidden value="<%= @distance %>" name="distance">
  <input type="text" hidden value="<%= @rent %>" name="rent">
  <select name="sort" id="sort" data-room-target="select" class="select-form-dd px-1 rounded quicksand grey bg-transparent shadow">
    <option value="">All rooms</option>
    <% if @place.present? %>
      <option value="distance-asc" <%= "selected" if params[:sort] == "distance-asc" %>>Distance - nearest to farthest</option>
      <option value="distance-desc" <%= "selected" if params[:sort] == "distance-desc" %>>Distance - farthest to nearest</option>
    <% end %>
    <option value="rent-asc" <%= "selected" if params[:sort] == "rent-asc" %>>Rent - lowest to highest</option>
    <option value="rent-desc" <%= "selected" if params[:sort] == "rent-desc" %>>Rent - highest to lowest</option>
    <option value="updated_at-desc" <%= "selected" if params[:sort] == "updated_at-desc" %>>Newest</option>
    <option value="updated_at-asc" <%= "selected" if params[:sort] == "updated_at-asc" %>>Oldest</option>
  </select>
</form>

app/views/rooms/edit.html.erb
<div class="container-fluid bg-p-options h-custom mb-custom d-flex align-items-center justify-content-center">
  <%= render "form", room: @room, locations: @locations %>
</div>

app/views/rooms/new.html.erb
<div class="container-fluid bg-p-options h-custom mb-custom d-flex align-items-center justify-content-center">
  <%= render "form", room: @room, locations: @locations %>
</div>

app/views/rooms/show.html.erb
<div class="container-fluid bg-repeat mb-custom py-4" data-controller="room">
  <div class="container-lg">
    <div style="min-height: calc(100vh - 87px)">
      <% if owner_signed_in? and current_owner&.rooms.include?(@room) %>
        <%= button_to "Edit Room", edit_room_path(@room), class: "rs-button d-block ms-auto mb-3 py-1 px-3", method: :get %>
      <% end %>
      <%= render "carousel" %>
      <%= render "room_description" %>
    </div>
    <div class="w-100 mb-3">
      <h3 class="text-center monsterrat heading-color bold">Property Location</h3>
      <p class="text-center quicksand grey" style="font-size: 15px;">
        <%= @room.location.full_address %>
      </p>
    </div>
    <div class="mb-sr" style="width: 100%; height: 500px;">
      <iframe
        src="https://www.google.com/maps/place?q=<%= "#{@room.location.latitude},#{@room.location.longitude}" %>&output=embed"
        frameborder="0"
        width="100%"
        height="100%"
        class="rounded shadow">
      </iframe>
    </div>
    <div class="w-50 mb-3" style="font-size: 15px;">
      <% if allowed_to_write_review? and @review.nil? %>
        <%= render "reviews/form", room: @room, review: Review.new, show_cancel_button: false %>
      <% elsif allowed_to_write_review? and @review.present? %>
        <%= render "reviews/editable_review", room: @room, review: @review %>
      <% end %>
    </div>
    <h3 class="text-center monsterrat heading-color bold mb-5">Room Reviews</h3>
    <div class="w-100 mb-3 <%= "review-grid" if @reviews.present? %>" style="font-size: 15px;">
      <% if @reviews.present? %>
        <% @reviews.each do |review| %>
          <%= render "reviews/review", review: review %>
        <% end %>
      <% else %>
        <p class="text-center quicksand grey mb-sr" style="font-size: 15px;">No reviews yet.</p>
      <% end %>
    </div>
  </div>

  <%= turbo_frame_tag "room_images_frame", class: "images-frame d-none", data: { room_target: "images" } %>
  <div class="backdrop d-none" data-room-target="imagesBackdrop" data-action="click->room#hideImages">
    <%= image_tag "close.svg", class: "images-close-icon" %>
  </div>
</div>