config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :occupants, controllers: {
    registrations: "occupants/registrations",
    sessions: "occupants/sessions"
  }
  devise_for :owners, controllers: {
    registrations: "owners/registrations",
    sessions: "owners/sessions"
  }
  
  resources :rooms
  get "rooms/:id/images", to: "rooms#images", as: "room_images"
  
  get "locations/new", to: "locations#new", as: "new_location"
  post "locations", to: "locations#create"
  delete "locations/:id", to: "locations#destroy", as: "location"
  get "/sign_in", to: "pages#options"

  post "room/:room_id/reviews", to: "reviews#create", as: "room_reviews"
  get "room/:room_id/reviews/:review_id/edit", to: "reviews#edit", as: "edit_room_review"
  patch "room/:room_id/reviews/:review_id", to: "reviews#update", as: "room_review"
  delete "room/:room_id/reviews/:review_id", to: "reviews#destroy"

  get "dashboard", to: "pages#dashboard", as: "dashboard"

  get "maps/render/location/:location_id", to: "maps#location_map", as: "location_map"
  get "maps/marker", to: "maps#marker_map", as: "marker_map"
  get "maps/results", to: "maps#results_map", as: "results_map"

  devise_scope :owner do
    get "owners", to: "owners/registrations#edit"
    get "owners/password", to: "owners/passwords#new"
  end

  devise_scope :occupant do
    get "occupants", to: "occupants/registrations#edit"
    get "occupants/password", to: "occupants/passwords#new"
  end
end

app/views/layouts/_flash.html.erb
<% if notice or alert %>
  <div class="f-modal rounded text-white text-center quicksand <%= notice ? "bg-success" : "bg-danger" %>" id="flash">
    <span class="opacity-75"><%= notice ? notice : alert %></span>
  </div>
  <script defer>
    var flash = document.getElementById("flash");
    var timeout;

    function fade() {
      flash.style.opacity = 0;
      setTimeout(() => flash.remove(), 100)
    }

    flash.addEventListener('click', () => {
      flash.remove()
      clearTimeout(timeout);
    })

    timeout = setTimeout(fade, 3000);
  </script>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container-fluid d-flex flex-column align-items-center justify-content-center">
  <%= link_to image_tag("landing_page/logo.png", style: "height: 30px; vertical-align: initial;"), root_path %>
  <h6 class="text-center quicksand grey" style="margin-bottom: 50px;">Copyright © 2023 Dormie. All rights reserved.</span></h6>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md bg-white shadow-sm">
  <div class="container-xxl">
    <%= link_to image_tag("landing_page/logo.png"), root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= render "layouts/session_manager" %>
    </div>
  </div>
</nav>

app/views/layouts/_session_manager.html.erb
<% unless owner_signed_in? or occupant_signed_in? %>
  <ul class="navbar-nav ms-auto mb-lg-0">
    <li class="nav-item me-3">
      <%= link_to "find a home", rooms_path, class: "nav-link" %>
    </li>
    <li class="nav-item me-3">
      <%= link_to "partner with us", new_owner_registration_path, class: "nav-link" %>
    </li>
    <li class="nav-item me-3">
      <%= link_to "sign up", new_occupant_registration_path, class: "nav-link" %>
    </li>
  </ul>
<% end %>

<% if owner_signed_in? %>
  <ul class="navbar-nav ms-auto mb-lg-0">
    <li class="nav-item me-3">
      <%= link_to "dashboard", dashboard_path, class: "nav-link" %>
    </li>
    <li class="nav-item me-3">
      <%= link_to "add new location", new_location_path, method: :get, class: "nav-link" %>
    </li>
    <li class="nav-item me-3">
      <%= link_to "list room", new_room_path, method: :get, class: "nav-link" %>
    </li>
  </ul>
  <%= render "layouts/dropdown/owner" %>
<% elsif occupant_signed_in? %>
  <ul class="navbar-nav ms-auto mb-lg-0">
    <li class="nav-item me-3">
      <%= link_to "find a home", rooms_path, class: "nav-link" %>
    </li>
  </ul>
  <%= render "layouts/dropdown/occupant" %>
<% else %>
  <%= button_to "login", sign_in_path, method: :get, class: "nav-button" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dormie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path("favicon.png") %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous" defer></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GM_KEY"] %>&callback=Function.prototype&v=weekly"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  </head>

  <body class="bg-white">
    <%= render "layouts/flash" %>
    <header class="sticky-top" style="z-index: 900;">
      <nav><%= render "layouts/nav" %></nav>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer><%= render "layouts/footer" %></footer>
  </body>
</html>